# rds variables
variable "project_name" {}
variable "environment" {}
variable "private_data_subnet_az1_id" {}
variable "private_data_subnet_az2_id" {}
variable "database_identifier" {}
variable "database_engine" {}
variable "engine_version" {}
variable "database_instance_class" {}
variable "database_security_group_id" {}
variable "db_master_username" {}
variable "db_master_password" {}
variable "database_name" {}
variable "parameter_groupname" {}